version: '3'

services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=SECRET
      - RABBITMQ_CLUSTER_NODENAME=rabbit@rabbitmq1
    
    # setting custom username/password
    env_file:
      ./rabbit-user.env
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq1-data:/var/lib/rabbitmq
    networks:
      - rabbitmq-cluster

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    environment:
      - RABBITMQ_ERLANG_COOKIE=SECRET
      - RABBITMQ_CLUSTER_NODENAME=rabbit@rabbitmq2
    # setting custom username/password
    env_file:
      ./rabbit-user.env
    ports:
      - "25672:15672"
      - "5673:5672"
    volumes:
      - rabbitmq2-data:/var/lib/rabbitmq
    networks:
      - rabbitmq-cluster

  rabbitmq3:
    image: rabbitmq:3-management
    hostname: rabbitmq3
    environment:
      - RABBITMQ_ERLANG_COOKIE=SECRET
      - RABBITMQ_CLUSTER_NODENAME=rabbit@rabbitmq3
    # setting custom username/password
    env_file:
      ./rabbit-user.env
    ports:
      - "35672:15672"
      - "5674:5672"
    volumes:
      - rabbitmq3-data:/var/lib/rabbitmq
    networks:
      - rabbitmq-cluster

volumes:
  rabbitmq1-data:
  rabbitmq2-data:
  rabbitmq3-data:

networks:
  rabbitmq-cluster:
    driver: bridge
