version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres:13.6-alpine
    env_file: ./pg.env
    volumes:
       - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: always
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.2
    env_file: ./pg.env
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "38081:80"
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
