version: '3'

services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=SECRET_1234
      - RABBITMQ_NODENAME=rabbit1@rabbitmq
    restart: always
    # setting custom username/password
    env_file:
      ./rabbit-user.env
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq1-data:/var/lib/rabbitmq
    networks:
      - rabbitmq-cluster

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    restart: always 
    environment:
      - RABBITMQ_ERLANG_COOKIE=SECRET_1234
      - RABBITMQ_NODENAME=rabbit2@rabbitmq
   # setting custom username/password
    env_file:
      ./rabbit-user.env
    volumes:
#      - rabbitmq2-data:/var/lib/rabbitmq
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq-cluster

  rabbitmq3:
    image: rabbitmq:3-management
    hostname: rabbitmq3
    restart: always 
    environment:
      - RABBITMQ_ERLANG_COOKIE=SECRET_1234
      - RABBITMQ_NODENAME=rabbit3@rabbitmq
    # setting custom username/password
    env_file:
      ./rabbit-user.env
    volumes:
      - rabbitmq3-data:/var/lib/rabbitmq
#      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
#    entrypoint: /usr/local/bin/cluster-entrypoint.sh

    networks:
      - rabbitmq-cluster

volumes:
  rabbitmq1-data:
  rabbitmq2-data:
  rabbitmq3-data:

networks:
  rabbitmq-cluster:
    driver: bridge
